name: Debug OIDC Connection
on:
  push:
    branches: [ main ]

jobs:
  debug-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is essential to request the token
      contents: read

    steps:
      - name: Debug OIDC Token
        run: |
          echo "Requesting OIDC Token from GitHub..."
          # The audience 'sts.amazonaws.com' is what we need for AWS
          TOKEN=$(curl -s -X POST -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" -H "Content-Type: application/json" "$ACTIONS_ID_TOKEN_REQUEST_URL" -d '{"audience": "sts.amazonaws.com"}' | jq -r .value)
          
          echo "Token received. Decoding JWT..."
          
          # Split the token and decode the payload part
          PAYLOAD=$(echo $TOKEN | cut -d. -f2)
          DECODED_PAYLOAD=$(echo $PAYLOAD | base64 --decode)
          
          echo "-----------------------------------"
          echo "OIDC TOKEN PAYLOAD:"
          echo "$DECODED_PAYLOAD" | jq .
          echo "-----------------------------------"
          
          # Extract and print the critical 'sub' claim
          SUB_CLAIM=$(echo $DECODED_PAYLOAD | jq -r .sub)
          echo "THE CRITICAL 'sub' CLAIM IS:"
          echo "$SUB_CLAIM"
          echo "-----------------------------------"